### ISSUE TITLE
Question about lazy commands

### ISSUE THREAD

**Issue by llaville** [theofidry/console#145]
Hello Théo,

In the context of https://github.com/box-project/box/blob/4.3.7/src/Console/Application.php#L78, how can we add new command (lazy loaded) without to modify the `getCommands()` contents ?

The symfony principle https://symfony.com/doc/current/console/lazy_commands.html seems not include in the Fidry Console !
Perharps I'm wrong, so please explain me.

PS: I've tried to implement `Fidry\Console\Command\LazyCommand` on a new command without to see any difference.

**Comment by theofidry** [comment]
The lazy commands you are pointing at are included in FidryConsole, however the lazy commands "automated way" only really applies to when you are using the full-stack framework. Implementing `LazyCommand` makes the `AddConsoleCommandPass` register the said command as a lazy command.

Box on the other hand does not use the full-stack framework at all, in fact it does not even have a container. So the way to create a lazy command is the "old way", without any magic.

**Comment by llaville** [comment]
>  So the way to create a lazy command is the "old way", without any magic.

I've a doubt to really understand your answer, because for me the standard SF way is to use the `CommandLoaderInterface`, feature that seems unsupported with Fidry Console ( https://github.com/theofidry/console/blob/main/src/Application/SymfonyApplication.php#L82-L85)

**Comment by theofidry** [comment]
> the standard SF way is to use the CommandLoaderInterface

Do you have an example out of the symfony framework usage (i.e. without the container & co.)?

**Comment by llaville** [comment]
> Do you have an example out of the symfony framework usage (i.e. without the container & co.)?

Not really ! But I expect to be able to set a custom factory command load (like this one https://github.com/llaville/docker-php-toolbox/blob/master/src/Console/Command/FactoryCommandLoader.php#L20) at Application construction before to run it.

In my project, of course I used a container, but in this way  `setCommandLoader()`
https://github.com/llaville/docker-php-toolbox/blob/master/config/set/common.php#L44-L57

**Comment by llaville** [comment]
I'll close this question because I've no more needed to solve this situation.
I've refactorised my code back to standard Symfony Console Command that support all features.

**Comment by theofidry** [comment]
I would like to keep it open. The answer to the original question will not change but I think changing the command loader should be allowed.

**Comment by theofidry** [comment]
Quick note for myself: after having a look it appears that registering the commands directly to `getDefaultCommands()` (in the context of a non-symfony app) is not really the way anymore. There is nothing wrong with it, but this indeed prevents lazy commands when it could otherwise be supported.

**Comment by theofidry** [comment]
This is more for the record as you already solved your case @llaville.

So lazy works but you need to manually handle it, i.e. you can implement `LazyCommand`, but since you need to return an instance of your command in `Application::getCommands()` you would need a bit more work like passing the dependent services by a callable, and your lazy command could call those when necessary.

This is an example where it uses a non lazy command and decorates it to make it lazy:

```php
final class ManualLazyCommand implements LazyCommand {
    private Command $command;

    /** 
     * @param callable():Command $commandFactory 
     */
    public function __construct(
        private readonly callable $commandFactory,
    ) {
    }

    public static function getName(): string
    {
        return 'app:lazy-foo';
    }

    public static function getDescription(): string
    {
        return 'Lazy foo description';
    }

    public function getConfiguration(): Configuration
    {
        return $this->getCommand()->getConfiguration();
    }

    public function execute(IO $io): int
    {
        return $this->getCommand()->execute($io);
    }

    private function getCommand(): Command
    {
        if (!isset($this->command)) {
            $this->command = ($this->commandFactory)();
        }

        return $this->command;
    }
}
```

Also reviewing https://symfony.com/doc/current/console/lazy_commands.html that somehow I missed:

```php
use App\Command\HeavyCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\CommandLoader\FactoryCommandLoader;

$commandLoader = new FactoryCommandLoader([
    'app:heavy' => function (): Command { return new HeavyCommand(); },
]);

$application = new Application();
$application->setCommandLoader($commandLoader);
$application->run();
```

This doc fails to mention that it is not a lazy command but a _soft_ lazy one. What that means is the command is indeed lazy, so if you execute a specific command from your app it will not be loaded. However there is one notable exception and it is the `list` command, as the description is not supplied. If `HeavyCommand` has the `#[AsCommand()]` attribute however, then it can be made into a full-pledge lazy command.

**Comment by theofidry** [comment]
And note to myself, with the work of #168 it should be possible to make lazy commands without it being as tedious as the example of `ManualLazyCommand` above.

**Comment by theofidry** [comment]
@llaville thanks again for that issue. It is now solved on the main branch and I should tag this very soon.

If you are curious the doc entry for the lazy commands has been updated.
