### ISSUE TITLE
Symlinked file does not exist

### ISSUE THREAD

**Issue by arnaudbroes** [theofidry/console#88]
PHPScoper requires `fidry/console` as a dependency. Your distributed production package (we use it through Composer) currently has a symlink in it that refers to a file `../tests/console` that does not exist. I'm assuming it's some kind of file from their unit tests that they do not ship in their distributed package.

Anyway, our build script was erroring out because of this when it needs to copy the files from PHPScoper (and its dependencies - hence `fidry/console`) to a different folder. 

For now, I managed to fix our build script by simply deleting the symlink, but I would love it if you could fix this in the Composer package.

**Comment by theofidry** [comment]
Ha indeed, I think it should be simply excluded along with `tests` for the git artifact

**Comment by theofidry** [comment]
Closed by #91
